apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - name: nginx
      image: nginx:1.17.2-alpine
      volumeMounts:
        - name: storage
          mountPath: /home/nginx
  volumes:
    - name: storage
      hostPath:
        path: /Users/jg20022/src/github.com/Ryoma0622/Udemy/Kubernetes/data/storage
        type: Directory
