apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
data:
  message: SGVsbG8gV29ybGQh
  keyfile2: WU9VUiBWRVJZIFNFQ1JFVCBGSUxF

---
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - name: sample
      image: nginx:1.17.2-alpine
      env:
        - name: MESSAGE2
          valueFrom:
            secretKeyRef:
              name: sample-secret
              key: message
      volumeMounts:
        - name: secret-storage
          mountPath: /home/nginx
  volumes:
    - name: secret-storage
      secret:
        secretName: sample-secret
        items:
          - key: keyfile2
            path: keyfile2
